################################################
# Lwe Configuration Template
#
# Configuration File Location : $HOME/.config/lwe/config.yml
#
################################################


# ai config
# name:
# resp_language:
ai:
    name: deepseek                          #Currently, only [deepseek] is supported
    apikey: your_openai_api_key
    baseurl: https://api.deepseek.com/chat/completions
    model: deepseek-chat

