################################################
# Lwe Configuration Template
#
# Configuration File Location : 
# Linux,Mac:
# $HOME/.config/lwe/config.yml
#
# Windows:
# %USER%\.config\lwe\config.yml
#
#
################################################



ai:
    name: siliconflow                                           #Currently, only [deepseek，siliconflow] is supported
    apikey: your_api_key                                        #Your  API key
    baseurl: https://api.siliconflow.cn/v1/chat/completions     #The API address of the model
    model: Qwen/Qwen2.5-Coder-32B-Instruct                      #The model name

